### ISSUE TITLE
axios.get via proxy using http-proxy-agent

### ISSUE THREAD

**Issue by maksimKorzh** [thomasnordquist/nominatim-geocoder#1]
Hello, Thomas, your geocoder is just great, but I was wondering whether it's possible to connect to nominatim.openstreetmap.org via proxy? I can't figure it out how to properly adjust axios.get(url....) request to use a given http agent, can you suggest something on how to achieve that goal? Please answer if you're available, thanks in advance, regards, Maksim Korzh.

**Comment by thomasnordquist** [comment]
Shouldn't it be as easy as this: https://github.com/axios/axios/issues/1679#issuecomment-407406296
There is also an example with socks-https-agent: https://www.npmjs.com/package/socks-proxy-agent

I personally prefer application wrapper like tsocks.

**Comment by maksimKorzh** [comment]
Fantastic! It works! Exactly what I needed! Thanks for your GREAT HELP!
